### ISSUE TITLE
Smudgeplot for allotetraploidy 

### ISSUE THREAD

**Issue by kashiff007** [KamilSJaron/smudgeplot#107]
**About your genome**

Plant genome with two diploid subgenomes, each with 2n=20, so in total 4n = 40.
This plant species came into existence with the hybridization of 2 similar species, each with 2n = 10. Allotetraploidy is evidently proven by karyotype with 40 chr (can’t share the figure here). It is also highly heterozygous. And it should be represented as AABB.
 
**smudgeplot**

We used highly accurate long-read HiFi sequencing for assembly. Same reads have been used to generate kmer (tried with different sizes from 21 to 51; all yielded the same results), and the frequency file was used for genomeScope2 and smudgplot. 

GenomeScope2 predicted the size almost near the size of the actual genome, and also, the unique and repeat region percentages are matchable with the post assembly genome analysis.

Rather smudgeplot predicted the genome diploid; AB. It also shows an area with AABB but have lower score. The plot looks like this:
![F798F34B-86A6-4D03-888A-69CE5EF1C936](https://user-images.githubusercontent.com/16431099/183064731-1709be8c-868a-408f-a4b5-b75ad9f6e07c.jpeg)

Also, the genomeScope2 plot showing only two humps which signifies the diploid. 
![8B2BEFB6-C635-4E72-A8DF-8958EF3F216B](https://user-images.githubusercontent.com/16431099/183065158-a640f58d-d60a-43e0-b286-25cde9c0beee.jpeg)

```
L=$(smudgeplot.py cutoff W6-48549-006_genome_kmer_fromHiFi.histo L)
U=$(smudgeplot.py cutoff kmer_counts.hist U)
echo $L $U 
26   800

jellyfish dump -c -L $L -U $U kmer_counts.jf | smudgeplot.py hetkmers -o kmer_pairs
smudgeplot.py plot kmer_pairs_coverages.tsv -o my_genome
```

Could you provide any suggestions to handle such complicated genomes?

**Comment by KamilSJaron** [comment]
Hi Kashiff,

I think you got it all sorted out - you know the ploidy, you know the genome size, everything but the "suggested ploidy" makes sense.

Smudgeplot searches for all k-mers that are different by exactly one nt and form a unique pair. Those usually are homologous regions. Now, you have allotetraploid, and it seems the two subgenomes are actually quite diverged already. K-mer spectra indicates there is no 4n peak (the peak representing the subgenomes that are exactly the same) and I suspect you had no problem to separate the subgenome in the genome assembly too. But that also means that there won't be that many homologous regions between the two subgenomes that are different in exactly one nucleotide - it will be usually more than that.

On the other hand, both the parental genomes are probably quite (or at least somewhat) heterozygous and therefore there are plenty of regions within both subgenomes that actually are one nt away from each other - sort of within-sub-genome heterozygosity, something we should call ABCC or AB--.

So it seems to me, that in your case the within-sub-genome heterozygosity is generating more k-mer pairs, than the two sub-genomes, and that is likely caused by their divergence. Do you know when the polyploidisaion occurred? I wonder if the two subgenomes came from distant lineages / species or if they diverged over time within this allopolyploid species.

**Comment by KamilSJaron** [comment]
Small comment, you can fit a tetraploid model in genomescope. If it converges on a different 1n coverage, you can also give it a prior on the coverage estimate. Or you could even try to fit the parameters using [Tetmer](https://github.com/hannesbecher/shiny-k-mers). That is something like genomescope, but it uses a bit different logic (it's more pop-geny, less combinatorics) might be more suitable for your genome given it's really designed for allotetraploids.

**Comment by kashiff007** [comment]
Thanks for the reply @KamilSJaron Yes we also suspected the same. Very little know about the organism's lineage. I am trying Tetmer, it looks promising for case like mine.

**Comment by kashiff007** [comment]
Tetmer is also confirming with same plot which means the genome is allotetraploid (2X peak) with high heterozygosity (smaller 4X peak).
<img width="1336" alt="image" src="https://user-images.githubusercontent.com/16431099/184139481-1e9e977f-5c0e-4e75-b4eb-261e267a0110.png">

**Comment by KamilSJaron** [comment]
Excellent
