### ISSUE TITLE
Could I use to these AAB kmer to make evaluation the assembled phased genome?

### ISSUE THREAD

**Issue by liufuyan2016** [KamilSJaron/smudgeplot#109]
I have troubles understanding my smudgeplot.  it look like this:
![smudgeplot_smudgeplot](https://user-images.githubusercontent.com/23466455/189506255-6ef2af3f-4ad6-4546-951f-f900db9c387f.png)
How to classified the kmer pairs into AA and AB  from the results ?  Could I use to theses kmers to make evaluation the assembled phased genome? For example , to re-aligned the assembled genome. Thank you!

**Comment by liufuyan2016** [comment]
Another question: The AAB results indicated the species is  allopolyploid and is not autopolyploids. The conclusion is right?

**Comment by KamilSJaron** [comment]
Hi, sorry for this huge delay. I started writing an answer, but I must have just forgotten to send it...

Anyway, your genome looks convincingly triploid. Guessing if it's auto- or allo- is actually very trechorous, because in any triploid genome the most likely allele type is AAB regardless (note these are not phased, so technically this can include all AAB, ABA, BAA cases, don't not necesarily indicate one haplotype is more distant than others).

However, you certainly CAN align these k-mers to the genome. 

First, use [smudgeplot extract](https://github.com/KamilSJaron/smudgeplot/wiki/smudgeplot-extract) to extract the k-mers of the triploid smudge (you can tell what are meaningful coverage/ratio boundaries). And then use [bwa-mem](https://github.com/KamilSJaron/smudgeplot/wiki/mapping-kmers-with-bwa) to locate them the the assembly. Note you should NOT phase your genome with it before checking if the Bs map to the same contig, because B does not have to always come from the same haplotype. So, if your assembly contains mulltiple haplotypes and it really happen to be allotriploid, you mind see that the minor kmer (the B) frequently maps to the same contigs, while As as well.

**Comment by KamilSJaron** [comment]
@liufuyan2016 did you succeed in phasing your genome?

**Comment by KamilSJaron** [comment]
Closing due inactivity, but if you have any input here, please reopen
