### ISSUE TITLE
Smudgeplot estimated incorrect ploidy level

### ISSUE THREAD

**Issue by rmormando** [KamilSJaron/smudgeplot#111]
Hello! I have a Saccharomyces cerevisiae genome that I have confirmed in the lab is tetraploid along with using [nQuire](https://github.com/clwgg/nQuire):

<img width="450" alt="image" src="https://user-images.githubusercontent.com/79812679/206302935-a77ba4de-09cd-4867-add4-2d6fd076c8ff.png">

```A good fit between ideal and empirical histograms is characterized by low SSR, positive slope with low standard error, as well as a high R2.```

^^ This is the rationale for determining what is the best ploidy level detected in a sample after running through the commands documented on their GitHub. Here we can determine the sample is tetraploid. 
  

Then, I wanted to generate plots so I came here to create a visual to further emphasize the ploidy from this sample. Using both KMC and Jellyfish (just to compare results) I used the following commands to generate this plot:

<img width="450" alt="image" src="https://user-images.githubusercontent.com/79812679/206305672-152ed130-ea04-454d-9bbd-ea70281ea9f1.png">

KMC and Jellyfish outputted the same plot:
<img width="450" alt="image" src="https://user-images.githubusercontent.com/79812679/206303706-8d1b8b27-c43d-421c-9835-0daccc3e8060.png">

Here is the link to the GenomeScope plot I generated as well (manually inputting a ploidy level of 4): http://genomescope.org/genomescope2.0/analysis.php?code=Rs3N3RepsJashtd6dJ6c

As you can see, smudgeplot is depicting this sample as diploid. I was wondering why that may occur - if there are certain memory standards or flags I could add on that might help the process? Or if using yeast data with this tool is a bit messy? I'm sorry if this is a lost cause I'm confused with the results and want to try and figure it out so I can use this as a figure since it's very pretty!

**Comment by tbenavi1** [comment]
Hello, thanks for reaching out. My first guess is that you need higher coverage. GenomeScope is estimating the genome size to be 7 Mbp but I believe it should be closer to 12 Mbp. This is because the coverage is too low.

**Comment by rmormando** [comment]
Thank you for your reply! Does that mean then that I should include a higher U value? I guess I'm wondering more so how do I account for a higher coverage? What's a good number to estimate or how do I go about estimating that value.

**Comment by rmormando** [comment]
http://genomescope.org/genomescope2.0/analysis.php?code=9DqKvxl7WoHmPncQ6xWG

I reran this sample with GenomeScope with a higher coverage (560) and it brought me the right length but still only had a peak or two.

**Comment by KamilSJaron** [comment]
Hi,

Did you see [this tutorial](https://github.com/KamilSJaron/smudgeplot/wiki/tutorial-saccharomyces)? 

It's also a yeast and it's tetraploid. But it has a lot better coverage and the coverage peaks are distinguishable, which is what allows us to pick an L that separates error and genomic k-mers. The same will be hard with your dataset - the error and potential 1n peaks are completely blended together - to the extend that you don't even know if there is any peak in between or not.

That makes using Smudgeplot hard - we heavily rely on the ability to sparate error and genomic k-mers. I worry that the plot is indeed hard to interprete.

I would also like to point out that it might be a bit sneaky to estimate ploidy with nQuire too. Inability to observe peaks implies there is quite high coverage variation (which is due to low coverage). Unless you look at coverage ratios of all heterozygous sites with reasonable  coverage (I guess ~35x is the "homozygous full-ploidy, whatever it is") and see a clear 0.25 / 0.75 peaks (suggesting AAAB and ABBB types of loci), I would not be confident about higher ploidy levels of this sample.

Damn, I wanted to just add my 2 cents and it ended up a superlong message again, haha. I really wanted to leave it to you Rhyker!

**Comment by tbenavi1** [comment]
I agree with everything Kamil said. And to be clear, when we say that you need higher coverage, we mean that you need to generate more sequencing data (and not that you need to change the parameters of the tools).

**Comment by rmormando** [comment]
The coverage I was using was 80X...

I went back and filtered the sequences with Filtlong and got a higher read length which brought the coverage down to ~48X, which is still pretty high for the data, but it resulted in essentially the same plot. Not sure what the solution would be to move forward with this tool but thank you for your feedback!
