### ISSUE TITLE
Issues with make exec/PloidyPlot

### ISSUE THREAD

**Issue by Kat0610** [KamilSJaron/smudgeplot#130]
Hello, 

i ran into issues when trying to install the dev version of smudgeplot. All dependencies are installed on the virtual machine that i am using and the Rscript install.R command also ran successfully. However when I run the `make exec/PloidyPlot` from the smudgeplot folder I get the following error: 

```
gcc -O3 -Wall -Wextra -Wno-unused-result -fno-strict-aliasing -o exec/PloidyPlot src_ploidyplot/PloidyPlot.c src_ploidyplot/libfastk.c src_ploidyplot/matrix.c -lpthread -lm
make: gcc: No such file or directory
make: *** [Makefile:25: exec/PloidyPlot] Error 127
```

Any help or advice would be appreciated!

**Comment by KamilSJaron** [comment]
Yep, I have literally spent the last hour trying to figure that one out! (today I was working on my Ubuntu computer at home).

It gets fixed by commenting out the third line of the `Makefile` (I also just pushed this change to the dev branch, so `git pull origin sploidyplot` will also do the trick).

Let me know if works now.

**Comment by Kat0610** [comment]
It's working now! Thank you

**Comment by KamilSJaron** [comment]
Amazing, would you consider posting here the plot?
