### ISSUE TITLE
unclear if genome is a diploid (Smudgeplot) or pentaploid (PloidyPlot)?

### ISSUE THREAD

**Issue by sallycylau** [KamilSJaron/smudgeplot#134]
Hi there! 

I have been struggling with interpreting my smudgeplot and genomescope results for a while and I am hoping if you might have some insights on this. My species is an Echinoderm & a wild specimen. Data was generated using PacBio HIFI (2 sequel II cells + 1 Revio cell) to achieve ~1.2Gb genome based on Genomescope. We have very limited background info on the species, so ploidy status and genome size is generally not sure.... but we had always assumed this was a diploid with a genome size of ~3GB based on exon & RADseq estimation.

I first generated genomescope results assuming ploidy=2 & Average k-mer coverage for polyploid genome = 40 which converged, but the fit is terrible.
![image](https://github.com/KamilSJaron/smudgeplot/assets/60337082/36b5587c-a13d-46f6-aaaa-11e1a7cf3d45)

I then ran smudgeplot (kmc.hist, L10 U2600, k21), and it showed it is a diploid with very high AB divergence, and it looks like this:
![smudgeplot_smudgeplot](https://github.com/KamilSJaron/smudgeplot/assets/60337082/c33a2145-ad6f-4d94-8082-2cebbd02b412)

I played with tetmer and the allotetraploid model (aabb) turned out to be a fit after a lot of manual adjustment: 
<img width="917" alt="Screen Shot 2023-09-27 at 5 43 06 pm" src="https://github.com/KamilSJaron/smudgeplot/assets/60337082/4919bae2-be17-4a2f-a84c-3a0877794471">

So I ran genomescope again but tried assuming ploidy=4, -k 21, -l 15 and the fit is better:
<img width="569" alt="Screen Shot 2023-09-27 at 5 49 28 pm" src="https://github.com/KamilSJaron/smudgeplot/assets/60337082/5dc52c6d-bed4-4caa-b49d-2c367658b25b">

I then thought maybe running PloidyPlot (the new smudgeplot implementation) would be a good idea... but the PloidyPlot now suggests it is a proposed pentaploid....
```
FastK -v -t4 -k21 -M20 -T5 1_HiFi.fasta 2_HiFi.fasta 3_HiFi.fasta -NFastK_Table
PloidyPlot -e10 -k -v -T5 -o_kmerpairs FastK_Table
smudgeplot.py plot -n 15 -t O -o O_smudge2.0 o_kmerpairs_text.smu
```
<img width="384" alt="Screen Shot 2023-09-27 at 5 48 42 pm" src="https://github.com/KamilSJaron/smudgeplot/assets/60337082/8bd5038b-b233-4b41-a04e-7cefb399481c">

>Just further information:
>I went ahead and assembled the genome with hifiasm (-l3) which gave me 2.4GB primary and 1.3GB alternate. BUSCO was C99.2%, S65.9%, D33.3%, F0.8%, M0.0%. I noted there was a lot of duplications, and given the high heterozygosity observed, I further ran purged_dups which gave me 1.9GB primary, 1.3GB alternate and BUSCO of C96.9%, S91.8%, D5.1%, F1.2%, M1.9%, which is still bigger than what genomescope estimated. 

>I also thought about contamination issue as I had been asked about this before (https://github.com/schatzlab/genomescope/issues/98) so I ran Kraken on the purged_dups assemblies and 98.89% (primary) and 99.97% (alternate) came back as unclassified, and my specimen was the only sample of the taxon the extraction/sequencing lab had handled so far. So I don't think there was contamination issue...

This genome is really puzzling to me (especially this is my first ever genome assembly!). I can clearly see 2 peaks in my genomescope plot, so diploid makes sense but I note that heterozygosity is high (3%).... However polyploid model always fits the data better (genomescope/tetmer/ploidyplot) and I just can't interpret what is my genome trying to tell me...! 

Any help would be much appreciated! Thank you! 

Best regards
Sally

**Comment by KamilSJaron** [comment]
Hi Sally,

sorry for the delay! I just somehow miss a notification of this issue.

The ploidyplot inference is wrong, I suspect that's because the coverage prior (-n 15). But in anyway, it seems that genomescope and smudgeplot kind of disagree on what is the 1n coverage. That is very strange to be honest - usually, the two converge on the same value (or at least, we always aim to generate models (plots) with matching coverages, because the 1n coverage is truly one value and can't be different between the two).

There are a bunch of examples like this on older smudgeplot issues (you can look at those that have smudgeplot and genomescope plots).

Finally, this is the moment when you need to start thinking about you organismal biology. Is any of the strangeness in anyway expected? What are we looking at?

I am just leaving for a paternity leave, so sorry if I won't get around to respond here again for a while....

**Comment by sallycylau** [comment]
Hi Kamil

Thanks for your reply & sorry it has taken me months to digest your feedback! (I needed to take a break from this genome :-) ) 

Sorry for a relatively long comment here again.... I ran Genomescope and PloidyPlot/Smudgeplot again, with k=21 and k=31, and results have gotten... weirder?

Running PloidyPlot/Smudgeplot (FastK) with no fixed n prior gave me a proposed triploid (k=21) and diploid (k=31). However, from eyeballing the smudges, I think diploid should be the slightly better answer here? 
<img width="849" alt="image" src="https://github.com/KamilSJaron/smudgeplot/assets/60337082/31b995dc-30b6-4a0f-8bf1-2e43be3386bd">

Running Genomescope (Meryl) with just -p 2 -k 21, and -p 2 -k 31, gave me the below. For which the estimated genome size got reduced by half at k=31! 
<img width="776" alt="image" src="https://github.com/KamilSJaron/smudgeplot/assets/60337082/c4fb5b83-dcc0-4c06-adac-5c248a9b61bd">

Running Genomescope (Meryl) but with a triploid mode this time didn't really make the model fit better. But I think the kcov is closer to what PloidyPlot/Smudgeplot thinks. Please also see the much better fitted tetraploid mode results in the first comment. 
<img width="881" alt="image" src="https://github.com/KamilSJaron/smudgeplot/assets/60337082/2a4ecd22-0a5f-4914-9aee-b45736952740">

More interestingly.... I estimated the genome size by counting kmers (Meryl) (N = n/C, n=total number of kmers, c= mean coverage/peak). K=21 gave me a genome size of 3.4Gb and K=31 gave me genome size of 3.8Gb, which are really far off from all but one Genomescope estimates! Even more fun, I actually struggled get a primary assembly from hifiasm assuming diploid that is larger than 3.0Gb (ranging between 1.X-3 Gb after trying many combinations). However, I got a 3.8Gb assembly with HiCanu and 3.4Gb assembly with Flye, but much more fragmented than any hifiasm outputs. 

I think at the moment I am struggling to make sense of 1) the ploidy information presented by PloidyPlot/Smudgeplot with varying kmer sizes, 2) I can't fit Genomescope correctly, and 3) genome size estimation in Genomescope is very different from kmer counting. I wonder if you may have any insights on this issue? Sorry if these are silly questions... this is my very first genome assembly project, but I have spent a few months dwelling over previous smudgeplot issues and I am still quite confused...

Regarding organismal biology - This is a brittle star. All this PacBio data was sequenced from a sample from the northern range of the study species. And we know that in the very far north, a very closely related tetraploid sister species exists. I also sequenced one sample of my study species from the southern range, using Illumina Novaseq, and GenomeScope happily gave me a well-fitted diploid model.... 
![linear_plot](https://github.com/KamilSJaron/smudgeplot/assets/60337082/9f63dd39-52c8-404e-8a5e-3698c0fc52e4)

The high heterozygosity of the Pacbio sample / this species, <50% unique sequences and high duplication judging from genomescope outputs are throwing me off... However, before I start to think about biology... I am on a mission to figure out what bioinformatic aspects I have missed! Thank you for all your insights in advance! 

 Cheers
 Sally

**Comment by KamilSJaron** [comment]
Eyeballing the smudges is the right thing to do! It does look like a diploid

Genome size in genomescope is quite literally: (sum(all k-mers coverages * counts) - sum(error coverages * counts)) / (1n_coverage * ploidy). THe reason why you get so much difference in genome sizes for individual models is the difference in 1n coverage and how much ends up estimated as errors, I think.

Say, for a second, you trust smudgeplot coverage inference better - you can try to make genomescope converge to that value by specifying the prior, or you can just open R and do the genomescope model yourself, where you fix kmer coverage instead of fitting it (This is a small tutorial on fitting manual models: https://github.com/KamilSJaron/oh-know/wiki/Manual-model-fitting)

Given you other brittle star sequencing run. I would think this one is not that far off the reality.

<img width="417" alt="Screenshot 2024-05-31 at 08 23 17" src="https://github.com/KamilSJaron/smudgeplot/assets/8181573/31452879-6730-4a92-9524-2e2a5f2fa3f7">

I wonder if your calculation is off by a factor of two because you did not divide by ploidy (usually we estimate haploid genome length, not diploid).

HOpe this helps
