### ISSUE TITLE
sploidyplot results: diploid or tetraploid

### ISSUE THREAD

**Issue by awesomedeer** [KamilSJaron/smudgeplot#155]
Dear Kamil, @KamilSJaron 
Thanks for the development and maintenance of this tool! Since I have the problem with RAM then I tried **sploidyplot** followed by the instructions from your slides and it worked and generated the smudgeplot figures. But I am not very clear that regarding the diploid strawberry example that smudgeplot prediction is correct only when kmer=51, not in other cases. 
Addditionaly, I was using HiFi reads to feed the tool, do I need to do some triming for them?
Would you mind checking my smudgeplot to see if it is diploid or tetraploid since AB looks stronger?
[trial_run_smudgeplot.pdf](https://github.com/user-attachments/files/16611817/trial_run_smudgeplot.pdf)
[trial_run_smudgeplot_log10.pdf](https://github.com/user-attachments/files/16611819/trial_run_smudgeplot_log10.pdf)
Best regards
Song  

_
We are very close to release a new version, which is now stalled for rising an offspring, but it's actually a well functioning version. If you take a look at the BGA23 tutorial, we already thought the update. THe new updated version is about 100000x faster (I exaggerate a bit, but just a bit - it's really a lot faster, the backend is written by Gene Myers). Anyway, if you take a loot at that, you might be able to run smudgeplot on a lot bigger genomes in a fraction of time: https://bga23.org/smudgeplot/

_Originally posted by @KamilSJaron in https://github.com/KamilSJaron/smudgeplot/issues/137#issuecomment-1899308542__

**Comment by KamilSJaron** [comment]
> Addditionaly, I was using HiFi reads to feed the tool, do I need to do some triming for them?

No, it's all good as is.

> Would you mind checking my smudgeplot to see if it is diploid or tetraploid since AB looks stronger?

"looks stronger" is missleading - although it has a "brighter square" it has fewer squares in total and is smaller (you see the total sizes in the panel on right)... Would you mind doing one more plot for me? I would like to see how would it look like if you rerun the plotting part with `--alt_plot` flag. This is a prototype for new plotting style, I think it might make a lot of difference on your data. 

Of course, biology sometimes likes to be very confusing. If your genome is not tetraploid, it at least have quite strong paralog structure of... AAAB type, which would be very unusual. I would bet some money on this being tetraploid to be honest, there is very little other potential explanation for seeing so many AAAB k-mers.

**Comment by awesomedeer** [comment]
Thanks for the detailed response. It's most likely a tetraploid. 
It's my pleasure to try this parameter.
Please see attached file.
[alt_plot_alt_smudgeplot.pdf](https://github.com/user-attachments/files/16672530/alt_plot_alt_smudgeplot.pdf)

**Comment by KamilSJaron** [comment]
Ah, the scaling of the y axis did not really work well. You could also specify the scale (specify something like `-ylim 120`), but I think I can see what's going on anyway...

This is a development version of the plotting algorithm that plots the data in a more raw format, which (to my surprise) quite often clarified the plot instead of obscured. The disadvantage is that it's not in nice squares as the original plot (we are working now on figuring out the clustering of peaks for this new way of representing the data, we are far, but it's not yet ready for a release).

To my surprise, there it also looks like the diploid smudge is brighter... Hmm, it still can be deceiving (it still applies that higher ploidy smudge, more potential coverage pairs it will cover and therefore will have more kmer pairs while lower overall density per square - the same thing as I explained).

Hmm, I will try to get the aggregation algorithm to work soon so we can test how it would change the smudge size esitmates...

**Comment by awesomedeer** [comment]
Thanks a lot Kamil! I definitely will use it when it release.

Best regards
Song
