### ISSUE TITLE
Ploidy inference of high heterozygous genome

### ISSUE THREAD

**Issue by Axolotl233** [KamilSJaron/smudgeplot#168]
Hello commuity,

I have troubles understanding my smudgeplot. I noticed that the master branch of smudgeplot updated in Sep 24 (Oriel version), and readme file declared that it will be updated in Oct 18. So I used sploidplot branch (which was updated in Oct 18). I have used follwing command to generate it.

```
FastK -v -t4 -k31 -M16 -T4 fastq_[12].fastq.gz -Ndata/FastK_Table
smudgeplot.py hetmers -L 12 -t 4 -o data/kmerpairs --verbose data/FastK_Table
smudgeplot.py all -o data/run data/kmerpairs_text.smu
```
and the result look like this:
[run_smudgeplot_log10.pdf](https://github.com/user-attachments/files/17523208/run_smudgeplot_log10.pdf)
[run_centralities.pdf](https://github.com/user-attachments/files/17523383/run_centralities.pdf)

My study species is a allotetraploid (2n=4x) and the potential progenitor is known, the genome size of this speciesi is about 720m based on flow cytomtry. Everything seems Ok of this figure and there have two peaks in AABB and AAAB. Howevery I noticed the the words "1n=30" in bottom of figure, which should indicate (if I did not make mistakes) the haplotype depth/coverge.  In my understand it should be the quotient of total sequence data divided by genome size of 1n. In my case, we sequenced 48G paired illumina reads, so the value of 1n should be 48G/720m = 66. I aslo found turning point in run_centralities.pdf at edge of picture, so I increased parameter -cov_max to 100 and -ylim to 300 when I ran smudgeplot.py all command, the result look like this:
[run_centralities.pdf](https://github.com/user-attachments/files/17523540/run_centralities.pdf)
[run_smudgeplot_log10.pdf](https://github.com/user-attachments/files/17523541/run_smudgeplot_log10.pdf)

Strangely, the generated smudge plot is clearly wrong. Although the position previously marked with AB still exists in minor kmer coverage = 0.5 and  total coverage of the kmer pair ~ 60, it missed mark, and the postion previously marked as AABB now marked as AB.  I don't know what causes this. Does the haplotype depth here refer to the depth of a single subgenome? Then how should the run_centralities.pdf be interpreted? Furthermore, my genome is highly heterozygous, I don't know if the differences between the subgenomes (A1 vs B1, A2 vs B2)  will be confused with the differences between the two haplotype genomes(n1 vs n2, n1 = A1B1, n2 = A2B2, A and B is two subgenome, Heterozygosity)  when generated smudgeplot.
![linear_plot](https://github.com/user-attachments/assets/26d51d58-131c-43b0-b07c-040a4fc23407)
![transformed_linear_plot](https://github.com/user-attachments/assets/d9b9093d-2776-4098-aabe-06e98208a21a)

**Comment by KamilSJaron** [comment]
Hi @Axolotl233 - all those plots look amazing!!!

GenomeSize in an allotetraploid is a funny thing. This is clearly an AABB, so what is the 720m genome size you talk about, A or B, or A and B?

This allotetraploid is not all too degenerated. Meaning, A and B still share tons of k-mers. You can see that in GenomeScope - there are clearly 4 peaks at 1n, 2n and 4n. And the 4n peak is large. Although, this model did not converge right, and actually it's not even the right model. You should try to add '-p 4 -l 30' parameters, it should help the model to converge to the what it should be...

GenomeScope reports back the size of a single haplotype (assuming A and B are of the same length). I think that if you did that model right, you you get ~300M genome size prediction, which would them mean that you  A+
B together is 720. Which is not all the much off what we expect.

> Does the haplotype depth here refer to the depth of a single subgenome? 

Yes, it's a single haplotype of a single subgenome. So if you will assemble both A and B as linear references, and all As and B reads will be mapped correctly, you expect ~60x coverage under each position (because two 30x haplotypes will map to the corresponding A and B subgenomes).

To me it all looks good and makes perfect sense!

**Comment by Axolotl233** [comment]
Hi @KamilSJaron,

Thank you for your insightful response. Here I want to clarify that the genome size (720m) is correlated with the A plust B (2n=4x=AABB, 720m = AB). Here I attached the results of genomescope (with -p 4 -l 31), Our previous results indicate that this allotetraploid originated from a hybrid polyploid event involving two closely related species. and you also point out that two subgenome have many the same kmers. This may have made the genome estimate smaller than expected, becasue some genome regions of two subgeonme in this allotereploid actully is like a autotetraploid.

![linear_plot_4](https://github.com/user-attachments/assets/9caedc85-1aaa-4b0a-8f0f-33bfc6032257)
![transformed_linear_plot_4](https://github.com/user-attachments/assets/23b40eb0-4e36-423b-aec7-8d98e6d637dc)

Anyway, here I still want to comfirm if I expect a haplotype depth of 60~ in this case, is it correct?  I am still a little confused about it.

Thank you

**Comment by KamilSJaron** [comment]
May I ask how did you make your histogram? FastK or something else? If not FastK, would you mind running that one for me? You should be able to get it out of the same database you used for smudgeplot... If you regenerate the histogram and re-run the model - is the genome size the same?

The reason why I am asking is because some k-mer counters do not deal well with repetitive kmers, FastK does and if you used that one, the genome size est can be quite wickedly accurate. In that case my guess would be that the genome is a bit smaller than what you have thought from flowcytometry (I guess you will find out once you assemble it). Other explanation would be if you have sequenced the heterogametic sex (if they have a heterogametic sex), that would also cause some underestimation because it assumes the sample ploidy of all the chromosomes.

And to confirm. You have 30x per haplotype, 60x per A, 60x per B and 120x of a collapsed haploid genome (which you will unlikely get due to divergence of A and B, so for assembly purposed you should calculate with 60x).

**Comment by KamilSJaron** [comment]
48e9 (totality of AABB) / 720e6 (expected haploid size of A + B) => 66 expected size of stack bellow A or B; the stack will contain two As and two Bs respectively; so per A must be ~30x;

Exactly what genomescope / smudgeplot predict.

**Comment by Axolotl233** [comment]
Thank you for your detailed explaination, my histogram (FastK.hist) used for genomescope analysis is created by fellow commands: 
```
FastK -v -t4 -k31 -M16 -T4 fastq_[12].fastq.gz -Ndata/FastK_Table
Histex -h1:5000 -G data/FastK_Table > data/FastK.hist
```
Here I have two questions, could you kindly give me some suggestion?

1. what does the output file "run_centralities.pdf" indicating? how to explain the point/curve of it.
2. if there have a probability that the heterzygosity of two subgenomes (A vs B) and two haplotype (n1 vs n2) could tangle together to make genome survey diffcultly.

Thank you

**Comment by KamilSJaron** [comment]
1. "centralities" is the measure we use to optimize the fit of coverage - it a measure that looks at the distances of points to the expected centers of coverage, which is the reason why factors of 2 will always be "also kind of matching" fits. I am not 100% happy with it yet, because of exactly that. You genome is clearly 30x, it should not be a 30x by a small margin...

2. Nah, the genomescope and smudgelpot are very clear in your case - these does not seem to be anything funky around.

**Comment by Axolotl233** [comment]
Hi,

Thank you for your response, for question 2, I just wonder some sepcific sneario in my allotertraploid (2n=4x=AABB). As I previous mentioned, this allotetraploid species were originated from two closely related species, and did not completely diploidzate. So I supposed that some sequence/genome-regions between two subgenome (A vs B) are exactly the same, which like a  autotetraploid. This case would make (in my understanding) heterzygousity not only observed between two haplotype (n1 vs n2), but also observed between two subgenomes, which could lead to an overexpansion of heterozygous sequences and collapse of homozygous sequence.  For example: I suppose subgenome A is exactly the same as subgenome B except SNP in some genome reigons,  so A1_A2_A1[B1]_A2[B2] (sequence A = B, but two haplotypes are heterzgyous) contribute to 2n peak of A1[B1] and A2[B2], which has the same contribution A1A1B1B2 (sequence A!=B, but two haplotypes are homozyous). In fact, I have encountered this problem in several recent allopolyploids from very related species, all of which were highly heterozygous. Could you kindly give some comments about it？

Cheers~

**Comment by KamilSJaron** [comment]
Would you like to join a drop-in Smudgeplot session this Friday 9:00 of UK time? Might be easier to talk...

**Comment by Axolotl233** [comment]
> Would you like to join a drop-in Smudgeplot session this Friday 9:00 of UK time? Might be easier to talk...

Ahhh, thank you for inviting me to join this session, unfortunately, it conflict with my schedule. if you need data, please contact me, I can share you some rawdata for testing.

**Comment by KamilSJaron** [comment]
The thing is - I don't think your data is in any way confusing! 

All smudgeplot is picking up are genuine bi-allelic sites. Those that are AABB or AAAB where A and B are one SNP away and there is no C that would be 1 snp away from either A or B. This means, that if you see a bright tetrploid smudge, there is a signal of non-degenerated tetraploidy. Lots of sites that are simply one nt away from each other.

More degeneration leads to dropout of 4n and 2n coverage peaks in exchange for 1n and 2n (so what in net happens to 2n is sort of dependent on what happened and we don't really have a good model to give a clear prediction). So the k-mer spectra could look moreless the same, perhaps with smaller 4n peak, but then your AAB and AB smudges would be much brighter than AABB / AAAB smudges, which does not seem to be the case. So, non-degenerated allotetraploid.

**Comment by Axolotl233** [comment]
Hi,

Thanks for your explanation! So you mean that K-mers of type AABC will be classified into AAB, and K-mers of type ABCD will be classified into AB in smudgeplot?

**Comment by Axolotl233** [comment]
The explanation of that how it worked with different type of allelic site completely cleared my confusion, I thought it would consider multi-allelic sites before. 

I am very grateful for your patience in answering my questions. anyway, smudgeplot is a very powful tool !!!

**Comment by KamilSJaron** [comment]
I am glad we got at the bottom of this
