### ISSUE TITLE
TypeError: fmean() got an unexpected keyword argument 'weights'

### ISSUE THREAD

**Issue by shankarkshakya** [KamilSJaron/smudgeplot#173]
Hi, I am having issues running the latest version of the smudgeplot v0.4.0dev. It fails at this stage. I have the .smu file

"smudgeplot.py all -o data/Scer/trial_run data/Scer/kmerpairs_text.smu"

Here is the entire error message.

_Running smudgeplot v0.4.0dev
Task: all

Loading data

Masking errors using local agregation algorithm
Total kmers: 2779100
        Genomic kmers: 2561420
        Sequencing errors: 217680
        Fraction or errors: 0.078
Infering 1n coverage using grid algorihm
Traceback (most recent call last):
  File "/usr/local/bin/smudgeplot.py", line 444, in <module>
    main()
  File "/usr/local/bin/smudgeplot.py", line 401, in main
    centralities = test_coverage_range(cov_tab, args.cov_min, args.cov_max, smudge_size_cutoff)
  File "/usr/local/bin/smudgeplot.py", line 296, in test_coverage_range
    cov_centralities.append(get_centrality(smudge_container, cov))
  File "/usr/local/bin/smudgeplot.py", line 288, in get_centrality
    return(fmean(centralities, weights=freqs))
TypeError: fmean() got an unexpected keyword argument 'weights'__

**Comment by KamilSJaron** [comment]
Hi, you have too old version of python for this. `fmean` had `weights` argument since certain version....

**Comment by shankarkshakya** [comment]
Thanks Kamil. I was able to download and run smudgeplot with conda. I am able to run and get all the .txt and .pdfs as output, however some plots are missing the smudge sizes (sample1.pdf here )and for some do have smudge sizes but missing the expected ploidy in all the plot (sample2.pdf)
[sample1.pdf](https://github.com/user-attachments/files/17787771/sample1.pdf)
[sample2.pdf](https://github.com/user-attachments/files/17787773/sample2.pdf)

**Comment by KamilSJaron** [comment]
Hi @shankarkshakya .

By smudgeplots it seems there are no visible smudges in the sample 1, sample 2 is less clear, there might be some smudges but they are all blurred (or alternatively, it's also just error as it is in sample 1).

Do you have corresponding GenomeScope plots? Do you see any clear genome peaks in the k-mer spectrum? If so, what L did you chose when selecting k-mer pairs?

Re missing label - in neither of the cases the ploidy is very clear from the plot. These are exactly the reason why we removed that "expected ..." label. We would like people to understand the plots and make the ploidy assessment themselves.

**Comment by shankarkshakya** [comment]
Thanks @KamilSJaron. here are two genomescope plots for sample1 and 2. They look very similar to me. L == 12 was used for selecting kmer pairs. 
![sample1_genomescope](https://github.com/user-attachments/assets/171a5c07-e3af-4d60-a1e3-c6a581f136a9)
![samp2_genomescope](https://github.com/user-attachments/assets/d8a6d129-5c8a-4633-bc5d-d6251c74b762)

I have attached one more sample from the same sequencing run, I am trying to see any evidence for tetraploidy.
[is_it_tetra.pdf](https://github.com/user-attachments/files/17801921/is_it_tetra.pdf)

Thanks again for your quick response.

**Comment by KamilSJaron** [comment]
I see what is going on here. You have rather modest coverage, ~14x so when you chose L = 12, you actually cut out tons of real genomic k-mers and although there will be plenty to remain in the dataset, the smudge corresponding to AB will appear very much on the border of the error line and smudgeplot (that nice curve in smudgeplot).

S, if you feel like, you can rerun smudgeplot with L = 8 or so, and it will looks a bit prettier. HOWEVER, if you wonder about tetraploidy, then there is no need. This is a very clear diploid. At least from the k-mer perspective. Meaning that IF it was a AABB tetraploid, A and B would be so diverged that there will no k-mer pairs found between them, all pairs you see would be AA' and BB', and the genomescope genome size esitmate would then be A+B (not just A or B).

I would be very comfortable just moving forward and treating the genome as diploid. Once assembled, you can align the genome to itself (with thngs like minimap2 or FastGA), if there is degenerated tetraploidy, you will be able to see it (because alignments can align homologous sequences of much higher divergences than single nt of 31-mers).

This goes a bit beyond smudgeplot interpretation so i will close the issue now :-) if anything feel free to open a new one

**Comment by shankarkshakya** [comment]
Thanks Kamil.

**Comment by gaoshan0405** [comment]
> Thanks Kamil. I was able to download and run smudgeplot with conda. I am able to run and get all the .txt and .pdfs as output, however some plots are missing the smudge sizes (sample1.pdf here )and for some do have smudge sizes but missing the expected ploidy in all the plot (sample2.pdf)谢谢你卡米尔。我可以用conda下载并运行smudgeplot。我能够运行并获得所有。txt和。pdf作为输出，但是有些图缺少涂抹大小（此处为sample1.pdf），并且有些图确实有涂抹大小但在所有图中缺少预期的倍性（sample2.pdf） [sample1.pdf](https://github.com/user-attachments/files/17787771/sample1.pdf) [sample2.pdf](https://github.com/user-attachments/files/17787773/sample2.pdf)

I have the same question as you: which Python version should I use?

**Comment by KamilSJaron** [comment]
@gaoshan0405 https://stackoverflow.com/a/78533680/29281675
