### ISSUE TITLE
Ricinus communis ploidy

### ISSUE THREAD

**Issue by sivico26** [KamilSJaron/smudgeplot#29]
Hi, I have troubles understanding my smudgeplots. 

I run an initial smudgeplot with ~14 Gbp data from SRA and as the results weren't the expected I downloaded more data (from the same [Project](https://trace.ncbi.nlm.nih.gov/Traces/sra/?study=SRP176405)) and rerun with ~139 Gbp. I passed them for trimmomatic before doing the kmer counting with KMC with almost the same code you put in the main README.

I have used following command to generate it

```
ls $path/Reads/Trimmed/*.fastq > FILES
srun kmc -k21 -t24 -m64 -ci1 -cs10000 @FILES kmer_counts tmp
echo "kmc db successful"
srun kmc_tools -t24 transform kmer_counts -cx10000 histogram kmer_k21.hist
echo "kmc histogram successful"

L=$(kmer_cov_cutoff.R kmer_k21.hist L)
U=$(kmer_cov_cutoff.R kmer_k21.hist U)
echo $L $U # these need to be sane values like 30 800 or so
srun kmc_tools -t24 transform kmer_counts -ci$L -cx$U dump -s kmer_k21.dump
srun hetkmers.py -k 21 -t 24 -o kmer_pairs < kmer_k21.dump
srun smudgeplot.R -i kmer_pairs_coverages_2.tsv -o ricinus_ploidy -t "Ricinus communis"
```

**Note:** the `srun` are there for execution in cluster, which uses Slurm.

And the results look like this:

[low_coverage_output](https://github.com/tbenavi1/smudgeplot/files/3015156/low_cov_ricinus.tar.gz)
[high_coverage_output](https://github.com/tbenavi1/smudgeplot/files/3015160/high_cov_ricinus.tar.gz)

Now, in the genome assembly [paper](https://www.nature.com/articles/nbt.1674), the authors got a genome size of ~350 Mbp and by other genome analyses, they strongly suspect it is a hexaploid. This does not make sense together with the smudge because it predicts triploid and diploid for low and high coverage respectively. However, I suspect the results are not clear because smudges are not separating well in the first place.

What do you think is happening here?
Should I rerun this analysis with some parameters modifications?
How should I understand these results?

Thank you for your help

**Comment by KamilSJaron** [comment]
Hi there, thanks for trying out smudgeplot!

The sequencing looks quite messy - the coverage variation is really big, which is what makes smudges on your smudgeplots so blurry. The paper is from 2010, so I suppose it will be more than a decade old sequencing, back then everything was messier.

The low coverage smudgeplot is very non-informative because of many kmer pairs yielding from genomic kmers paired with sequencing errors (because of low L) and the triploid estimate is apparently off (I am actually not sure how could the algorithm assign AAB label to that smudge. If something it should be AB). Using smudgeplot with less than 50x is always sneaky and if you have more data there is no reason why not to use it.

The high coverage dataset still suffers by the coverage variation (the only detected smudge is all over the place), but I think the reason why you don't see more smudges is different. It will be a choice of L and U. L is supposed to remove sequencing mistakes (I would choose something like 100 I suppose), U is an upper boundary for kmers to filter out mt DNA and stuff like that, that can be really high and I suppose the algorithm have given you way too small number that would be good for your sample (I would choose U = 3000). I expect that you U will be 400 which cut out all kmers that 

So, what L/U you used? Would you mind uploading here also a kmer histogram? You can plot it using Genomescope. Using the kmer histogram we can figure if the AB smudge was labeled correctly.

**Comment by KamilSJaron** [comment]
I am closing this issue as inactive. If you would have any more question, just add a new comment and I will reopen it.
