### ISSUE TITLE
Plukenetia volubilis attacks again: Allopolyploid or Autopolyploid?

### ISSUE THREAD

**Issue by sivico26** [KamilSJaron/smudgeplot#45]
Hi again Kamil,

I noted that the [preprint](https://www.biorxiv.org/content/10.1101/747568v1) of smudgeplot is finally released! And for that, I congratulate to you and the other authors. I am sure you are really proud of this amazing job.

From the preprint, one section caught my attention: Allotetraploid vs Autotetraploid. There, you discussed (if I understood correctly) that based on the proportion of kmers AAAB vs AABB (generated by genomescope2) you can infer if you are dealing with an autopolyploid or an allopolyploid.

You can imagine I could not avoid wondering which would be the case for my plant, _Plukenetia volubilis_, which we previously analyzed together in #36 and determined it was a tetraploid.

I relaunched genomescope2 with the same histogram we used in #36, and here you can see the [result](http://genomescope.org/analysis.php?code=XU4ieWwELZjptFnWUpUe). We can see that the proportion of AAAB is almost inexistent and the proportion of AABB is really high. Hence, following the preprint logic, we would say it is an allotetraploid, right?

However, I noticed that the proportion between these two is different from the ones we see in the smudgeplot. In fact, in my particular case, there are no AAAB kmers in the summary provided by smudgeplot. I know that smudgeplot deals with heterozygous kmers, but I wonder if there is a relation between the proportions of kmers of both programs and if you can infer the Allo vs Auto feature from smudgeplots as well. 

Beforehand, thanks for your comments, and I am really happy that we have something to cite and give the corresponding credits.

PS: In case the genomescope result doesn't load (I am trying but it does not for some reason, hopefully it will for you), I will append the model results here:

```
GenomeScope version 2.0
input file = user_uploads/XU4ieWwELZjptFnWUpUe
output directory = user_data/XU4ieWwELZjptFnWUpUe
p = 4
k = 21

property                      min               max               
Homozygous (aaaa)             67.8924%          95.0473%          
Heterozygous (not aaaa)       4.95271%          32.1076%          
aaab                          0%                6.61037%          
aabb                          4.90424%          20.3037%          
aabc                          0.0484783%        2.8474%           
abcd                          0%                2.34608%          
Genome Haploid Length         250,542,571 bp    251,341,685 bp    
Genome Repeat Length          87,932,927 bp     88,213,392 bp     
Genome Unique Length          162,609,643 bp    163,128,293 bp    
Model Fit                     69.9239%          90.834%           
Read Error Rate               0.0690489%        0.0690489%    
```

**Comment by tbenavi1** [comment]
Thank you so much for using our tools and taking a look at our preprint!

To answer your question, the results from genomescope 2.0 for aaab and aabb are nucleotide level values while the results for AAAB and AABB from smudgeplots are k-mer level values. More specifically, the value of 12.6% for your data for aabb means that 12.6% of the nucleotides across the monoploid genome are of the form aabb. The value of 70% for AABB means that 70% _of the k-mer sibling pairs_ are of the form AABB. So, the higher value of AABB makes sense because we are taking a proportion only of k-mer sibling pairs (one SNP different), not of all k-mer pairs. 

In terms of allotetraploid versus autotetraploid, it seems quite clear from both genomescope and smudgeplot that your sample is allotetraploid. I believe you can also infer allo vs auto using smudgeplots with a high proportion of AAAB giving evidence for autotetraploid and a high proportion of AABB giving evidence for allotetraploid.

Finally, the reason the website with the results doesn't load is because we forgot to update the link for the results for the new 2.0 version of the website. To see your results, please go to genomescope.org/genomescope2.0/analysis.php?code=XU4ieWwELZjptFnWUpUe. Thanks for pointing this out and we will fix it shortly.

**Comment by sivico26** [comment]
Thanks for your thoughts and quick reply Kamil, all this analysis will definitively improve the development of our projects. 

I wish you the very best!

**Comment by sivico26** [comment]
Dear @tbenavi1, I would like to ask you a fast question regarding genomescope2. I was not sure where to put it, because the [genomecscope2](https://github.com/tbenavi1/genomescope2.0), and didn't seem appropiate in the original genomescope repo.

Anyway, what does exactly the "dup" estimate mean? I did not find any explicit mention to it in the preprint (I apologize if I missed it). I did notice that it has a broad range along the genomes you evaluated: from less than 1 to ~6.

In the case of _Plukenetia volubilis_ this value is 3.5. Does this say something about the genome?

Thanks in advance.
