### ISSUE TITLE
smudgeplot cutoff

### ISSUE THREAD

**Issue by fjruizruano** [KamilSJaron/smudgeplot#49]
Hi!

First at all, thanks for this great idea.

I have trying to run the smudgeplot protocol, but when I launch "smudgeplot.py cutoff" with different boundaries from  1 to 10000, I always get the same cutoff. This is my code:

```
kmc -k21 -t20 -m64 -ci1 -cs10000 -fq @list.txt kmer_counts tmp
kmc_tools transform kmer_counts histogram kmer_k21.hist -cx10000
smudgeplot.py cutoff kmer_k21.hist 20
smudgeplot.py cutoff kmer_k21.hist 3000
```

Am I doing something wrong?

Cheers.

**Comment by KamilSJaron** [comment]
Hello @fjruizruano, `smudgeplot.py cutoff` is a script that gives you a suggestion of L or U boundary. So you should run

```
smudgeplot.py cutoff kmer_k21.hist L
smudgeplot.py cutoff kmer_k21.hist U
```

to get a reasonable **L**over and **U**upper boundary. This you will subsequentially feed to `kmc` to get the bulk of kmers that will be used to find the kmer pairs. Does it make sense?

I suppose I could add a condition that verifies that the boundary is L or U and screams otherwise, but otherwise, it's not a really a bug, the script works as expected.

**Comment by fjruizruano** [comment]
Thanks a lot for the clarification.
It is now working!

Bests.

**Comment by KamilSJaron** [comment]
Cool. For the furture reference:
 - [some information about choosing L and U](https://github.com/KamilSJaron/smudgeplot/wiki/chosing-L-and-U)
 - [description of smudgeplot.py cutoff algorithm](https://github.com/KamilSJaron/smudgeplot/wiki/smudgeplot-cutoff)
