### ISSUE TITLE
GenomeScope and Smudgeplot_interpretation of results

### ISSUE THREAD

**Issue by kiraza-lab** [KamilSJaron/smudgeplot#74]
Dear Kamil,
first of all I'd like to thank for the GenomeScope2.0. It's very useful for the first estimation of genome. Based our results, the study organism underwent  a recent genome doubling via allotetraploidization, i.e. the species is allotetraploid (species I). The WGD accompanied by TE activation and intensive genome reshuffling, i.e. the species characterized with a prominent genome instability. According to the flow cytometry data, its genome size is about 862 Mb. I sequenced its genome with low coverage (about 10x). I got these results:
p=2 (for diploid genome): http://qb.cshl.edu/genomescope/genomescope2.0/analysis.php?code=F37gCMs8PU6RKwGhFIOR
the proposed genome size: 316 Mb
smudgeplot:
![my_genome_allotetra_val_smudgeplot](https://user-images.githubusercontent.com/73155017/96975475-af6c4580-1544-11eb-8b02-3fd8c425438d.png)
![my_genome_allotetra_val_smudgeplot_log10](https://user-images.githubusercontent.com/73155017/96975478-b09d7280-1544-11eb-9f0b-ed56926f5ef7.png)

p=3 (for triploid genome): http://qb.cshl.edu/genomescope/genomescope2.0/analysis.php?code=16CJdcLJC5cIJIxmdUml
the proposed genome size: 85 Mb

Also, I tested the another species (hidden autotetraploid, high genome coverage) and obtained these results:
http://qb.cshl.edu/genomescope/genomescope2.0/analysis.php?code=P0FAiWjdxiMRSaWeNIou
![my_genome_val1_first_smudgeplot](https://user-images.githubusercontent.com/73155017/96996046-64106200-1559-11eb-95ca-bb8727b283ad.png)
![my_genome_val1_first_smudgeplot_log10](https://user-images.githubusercontent.com/73155017/96996058-6672bc00-1559-11eb-9e93-93877ee8582a.png)

May I ask you to help with the interpretation of these results (the first case)? I have some suggestions (too low coverage; high heterozygosity and high repetitiveness of the genome). Am I right that in second case we can observe three peaks=three subgenomes?
Kira.

**Comment by KamilSJaron** [comment]
Hi Kira, unfortunately, the first two cases have too low coverage for smudgeplot or genomescope to be very informative. I know that this is not a very satisfactory answer, but without more coverage, there is not much these algorithms can do. The triploid model also looks like it did not converge well on the 1n coverage. Hence I would guess a more accurate estiimate will be about 2x higher (the model failed to converge due to low coverage, as I wrote before).

The hidden tetraploid (the third case) has a nice coverage, but it does not look like a tetraploid to me. There is a very clear triploid signal both in smudgeplot (AAB smudge) and genomescope (clear 3 peaks).  How do you know it's a tetraploid?

**Comment by kiraza-lab** [comment]
Dear Kamil,
thank you so much for the reply. I suspected that for the first and second cases the coverage was not enough and you dispelled doubts about it. I need higher coverage of sequencing.
Previously we obtained indirect evidences that a recent WGD took place in genome evolution in the third case, and therefore we suggested that its genome is a tetraploid.
Kira.

**Comment by KamilSJaron** [comment]
I suspect triploidy could possibly generate signals similar to WGD, I would keep mind open to both possibilities and hope that downstream analyses of the genome will help to sort which one it is (but I would totally bet on triploidy, the signal is very very clear and also really hard to be mistaken for any even-counted ploidy). I recommend checking also nQuire, it's a very handy software estimating ploidy from the coverage support of heterozygous variants. This being said, I don't know what specific indirect evidence you have, therefore it's hard for me to give you a more confident answer.

Is your question resolved? Can I close the issue?

**Comment by kiraza-lab** [comment]
Dear Kamil,
I have another question: is it possible that  in our case the genome consists of three subgenomes and it is hexaploid?

**Comment by KamilSJaron** [comment]
Very unlikely. If the genome was a hexaploid we would see at least some kmers with higher ploidies (AAABBB, AAAABB, AAAAAB but also some low frequency AABB, AAAB for regions deleted in some of the subgenomes). The only (still unlikely) possiblity I see, that the genome is a very very recent hexaploid with two differentiated genomes (AAAABB) and the within A and within B divergence is so low that there the labeling is shifted (that the AAB smudge is in fast AAAABB and the AB is AABB). However, this explenation is really a strech and althought I have seen quite a few recent tetraploid genomes that looked like diploid due to this problem of label shifts, I have not seen this with any higher ploidy.

**Comment by kiraza-lab** [comment]
Dear Kamil,
thank you so much for the explanation and help with the interpretation of the results. My question is resolved, so the issue can be closed.
Kira.
