### ISSUE TITLE
Killed process on smudgeplot hetkmers

### ISSUE THREAD

**Issue by ddelgadillod** [KamilSJaron/smudgeplot#77]
**What did you do**

Tell us about the problem. what is the version of the software you used (smudgeplot -v)? What was the input (possibly with a few example lines)? What is the command you run? What is the error output you get? And what you have expected to see instead?

Hi I'm trying to obtain smudgeplot for Potato genome, I installed all dependencies for R and python scripts when run hetkmers command after a while process is killed
```console
user@corp-esc-lnxu01:~/GenomeAssemblies/Potato$ jellyfish dump -c -L $L -U $U kmer21_counts.jf | smudgeplot.py hetkmers -o kmer_pairs
Running smudgeplot v0.2.3dev
Task: hetkmers
Kmers and coverages loaded.
Killed
```

L and U are 10 and 2500 respectively

Do you suggest any to run previous command, and obtain smudge_plot, currently it runs over Python 2.7 and R 3.6, a previous test with fastq files for short genomes (bacteria) run satisfactory and I can see smudge_plot for it.

**Comment by KamilSJaron** [comment]
This looks like the server/computer where you run the job has killed it because it was requiring too much RAM memory.

you can take a look at the [approximate memory requirements](https://github.com/KamilSJaron/smudgeplot/wiki/smudgeplot-hetkmers) or better, try to get the kmer pair using the modified kmc code [described in the main README file](https://github.com/KamilSJaron/smudgeplot#usage). it's faster and it requires much less memory too.

Hope this helps.

**Comment by KamilSJaron** [comment]
closing for now, reopen if the problem persist
