### ISSUE TITLE
AA smudges

### ISSUE THREAD

**Issue by nhartwic** [KamilSJaron/smudgeplot#82]
I've been playing with smudgeplot. Haven't had any real troubles running it, but I suspect most of my datasets lack the coverage needed to get accurate inference. Mostly the results make sense to me even if I don't trust them. One thing that I have been noticing on some smudgeplots is the presence of an AA peak. What is an AA peak? I thought smudgeplot worked by looking at putative heterozygous snps in kmer frequencies. How do you get an AA type kmer pair? An example image shown below...

![Skelm7_FDSW202619156-1a_smudgeplot](https://user-images.githubusercontent.com/13526494/105231121-3a94b180-5b1b-11eb-8d4a-82f3f0d6697c.png)

**Comment by KamilSJaron** [comment]
Hi @nhartwic , Smudgeplot primarily aims to estimate 1n coverage and base all the other aspects on that.

The draft 1n estimate is done using kernel smoothing of subsets of Nomalizes minor kmer coverages ([code] (https://github.com/KamilSJaron/smudgeplot/blob/master/R/estimate_1n_coverage_1d_subsets.R) that takes the subsets; [code](https://github.com/KamilSJaron/smudgeplot/blob/master/R/get_1d_peaks.R) that estimate coverage peaks in each subset). This draft estimate is then defined using the brightest smudge, in idea case it will change the estimate only a tiny bit ([code](https://github.com/KamilSJaron/smudgeplot/blob/master/R/estimate_1n_coverage_highest_peak.R)). This code is a result of an effort to make it work unsupervised on as many genomes as possible, it's not particularily elegant because we always found some datasets that needed some exceptions.

Anyway, once the 1n coverage is estimated, then the individual peaks are annotates by their coordinates on the x and y. y / 1n coverage is the number of haplotypes of that peak and the number of haplotypes expanded by the ratio gets how many As and Bs are there. Of couse, if there is a smudge with 0.45 minor cov and is diploid, it will be rounded to AB (not 0.55A0.45B). And if things go really wrong, things get rounded to minor coverage < 0.25 to AA. Which is obviously non-sense. These are always messed up smudgeplots, perhaps I could add a bit of code that will refuse to annotate the smudges if there is a messed up AA case.

**Comment by nhartwic** [comment]
Thank you for the explanation. Makes sense. I don't know if refusing to annotate is desirable. Probably just spit out a warning and add a "likely failure modes" section to the readme documenting that the presence of a significant AA smudge likely indicates that 1n coverage was incorrectly estimated.
