### ISSUE TITLE
Is the kcov of genomescope more informative than the estimated haploid coverage of smudgeplot?

### ISSUE THREAD

**Issue by BlueBerrySun** [KamilSJaron/smudgeplot#88]
Hi ,
Thanks for developing the nice tool !
I tried the rainbow trout genome which you mentioned in  #17 with these [reads](https://www.ncbi.nlm.nih.gov/sra?term=ERP003734%5BAll%20Fields%5D%20AND%20%22platform%20illumina%22%5BProperties%5D&cmd=DetailsSearch).

I used following commands

> kmc -t4 -ci1 -cs10000 -k25  @FILES kmc .
> kmc_tools transform kmc histogram hist
> L=$(smudgeplot.py cutoff hist L)   # L=14
> U=$(smudgeplot.py cutoff hist U) # U=1500
> kmc -t4 -ci14 -cx1500  -cs10000 -k25  @FILES kmcdb .
> smudge_pairs kmcdb cov.tsv seq.tsv >out.tsv
> smudgeplot.py plot cov.tsv

> genomescope.R -i hist -p 2 -k 25 -o genomescope

>  smudgeplot.py plot -n 20 cov.tsv

and then got these results

(smudgeplot without setting haploid coverage)
![new_smudgeplot](https://user-images.githubusercontent.com/68422304/120094686-7a684700-c154-11eb-9b50-bfdfe50a3703.png)
(  The length estimated  by genomescope2 is so accurate , similar as the paper said  “The total size of the resulting assembly was 1.9 Gb ” .  Because I thought the kcov was more informative, I ran another smudgeplot and set haploid coverage equal to 20. )
![linear_plot](https://user-images.githubusercontent.com/68422304/120094690-805e2800-c154-11eb-8e6b-0dc6be775fe4.png)
(smudgeplot after adjusting haploid coverage )
![cov20smudge_smudgeplot](https://user-images.githubusercontent.com/68422304/120094698-88b66300-c154-11eb-94bb-0bf893f38415.png)

In the first smudgeplot , I think the misestimated haploid coverage has led to a right result. And my understanding of the second smudgeplot is same as the tutorial strawberry example, duplication signal is relatively stronger than the heterozygosity signal .

I am confused whether my thought is right.

Best wishes,
Sun

**Comment by KamilSJaron** [comment]
Hi Sun, thanks for exploring stuff with smudgeplot, it's really useful to see more datasets analysed! Long story short, you got it right. Here is a more complete elaboration:

This is a sneaky one. The rainbow trout (as all salmonids) is supposedly a decayed tetraploid. So, I would expect to see probably 3 distinct peaks - 1n, 2n, and 4n. Where 1n will be the heterozygosity peak, 2n the core genome of sequences that already diverged between the two subgenomes, and 4n for those bits that still happen to be the same. We also expect, that plenty of the 2n kmers will have a similar kmer with about the same coverage (those are not the same but 1 nt divergent between the subgenomes).

That's why I thought it would be interesting to get the smudgeplot in the first place.

Now, the reality is a bit stranger, smudgeplot seems to have just a single bright smudge, so which one is it? The heterozygosity one (1n <-> 1n kmer pairs) or the subgenome homolog one (2n <-> 2n kmers)? To get at the bottom of this, looking at GenomeScope is certainly super useful, but how comes there are 2 peaks at best? Which 2 we see? Could be that the genome is very homozygous (could be if it's some sort of stock population) and the two distinct peaks we see are 2n and 4n (which is the model you fit). And with a model like this, the genome size is as expected (which is a reassuring sanity check), so I would probably conclude that it's just a very homozygous genome.

So, why sneaky? For a wild-caught individual I would expect at least some detectable heterozygosity, so not knowing the genome size, I would probably think the first smudgeplot is right and the genomescope should fit twice lower kmer coverage. When interpreting these it's really important to consider the expectations as well.

**Comment by BlueBerrySun** [comment]
Hi Kamil,

Thank you for your elaboration which let me understand more clearly how to combine these results to analyze.

And I'm sorry that my link failed :( , I ran with reads sequenced by illumina first and I ran with reads sequenced by 454 in recent days.

**commands**
> kmc -ci1 -cs10000 -k25 -t10 @FILES kmc .
> kmc_tools transform kmc histogram hist
> L=$(smudgeplot.py cutoff hist L) # L=11
> U=$(smudgeplot.py cutoff hist U) # U=280
> kmc -ci11 -cx280 -cs300 -k25 -t10  @FILES kmc_11_280 .
> smudge_pairs kmc_11_280 cov.tsv seq.tsv >out.tsv
> genomescope.R -i hist -o genomescope -p 2 -k 25

**results**

![smudgeplot_smudgeplot](https://user-images.githubusercontent.com/68422304/120741138-13b5a580-c527-11eb-8a68-251c5213074e.png)


![linear_plot](https://user-images.githubusercontent.com/68422304/120451024-9f162600-c3c3-11eb-8438-9ec073767bb0.png)

**summary.txt**

illumina
![rainbow](https://user-images.githubusercontent.com/68422304/120451873-5f9c0980-c3c4-11eb-9086-932e7b0776c6.png)

454
![rainbow454](https://user-images.githubusercontent.com/68422304/120452292-b0abfd80-c3c4-11eb-9595-8d54bb912dff.png)

The results are quite different from before. I don't know much about sequencing，I'm more receptive to the previous results made by reads sequenced by illumina for the better model fit and accurate haploid length.  And the paper said the sample was a single homozygous doubled haploid YY male , this also supports the previous results more , right? I'm wondering whether these differences came from different sequencing methods and  sequencing by illumina would be preferable. It's really sneaky and thanks again for helping me understand it.

Best Wishes,
Sun

**Comment by KamilSJaron** [comment]
Yeah, 454 is old, not as precise and the dataset has lot lower coverage, which makes it lot harder for genomescope to fit the right model and in this case, it (apparently) missed the heterozygous peak that was blended too much with the error peak, as a consequence the genome size is half of the one you would expect... If I missed something let me know, I wrote this in rush :-) .

**Comment by KamilSJaron** [comment]
I will close it for now, if any other questions, don't hesitate to reopen it.
