### ISSUE TITLE
ask for help: Smudgeplot erro

### ISSUE THREAD

**Issue by cuixy1994** [KamilSJaron/smudgeplot#95]
Hello, 

I had the same problem with [smallfishcui] in smudgeplot (https://github.com/KamilSJaron/smudgeplot/issues/55#issue-636083169).  I'm using NGS data.

I get the message like this error:

######################
Error in if (round(peak_frame_4$cov[1]/peak_frame_2$cov[1]) >= 2) { : 
  missing value where TRUE/FALSE needed
Calls: estimate_1n_coverage_1d_subsets
Execution halted

Here is my code:

kmc -k21 -m24 @FILES kmcdb ./
kmc_tools transform kmcdb histogram kmcdb_k21.hist -cx10000
L=$(smudgeplot.py cutoff kmcdb_k21.hist L)
U=$(smudgeplot.py cutoff kmcdb_k21.hist U)
echo $L $U # these need to be sane values
## 160  260 
kmc_tools transform kmcdb -ci"160" -cx"260" dump -s kmcdb_L"160"_U"260".dump
smudgeplot.py hetkmers -o kmcdb_L"160"_U"260" < kmcdb_L"160"_U"260".dump
smudgeplot.py plot kmcdb_L160_U260_coverages.tsv

How did you solve the problem for him ?  I have an attachment in the back.

Thanks,
Cui

When you say:
https://github.com/KamilSJaron/smudgeplot/issues/55#issuecomment-652349701

[kmcdb_L160_U260_coverages.zip](https://github.com/KamilSJaron/smudgeplot/files/8013933/kmcdb_L160_U260_coverages.zip)

**Comment by KamilSJaron** [comment]
Hi Cui,

I guess I should fix this error finally.

It is (till now every time) caused by L and U being too close to each other - The x axis of smudgeplot is minor / (major + minor), where major and minor are coverages of the more and less covered kmer in a k-mer pair. So if you selecting kmers that are 160 to 260x, then it the minimal value of minor / (major + minor) is 0.38, and causes that the whole left side of the plot would be blank.

The error itself is a problem because the algorithm needs some of points with coverage ratio lower than that and use it to guess the ploidy right, which is also the reason why I have not really made a decent workaround.

So for now I would recommend chosing better values of L and U. What is your expected 1n coverage approximately?

**Comment by cuixy1994** [comment]
The situation of this sample is as follows:
coverage: 61     meandepth: 4.5

I chosed the values of L=10  and U=260, the final analysis was the same.
I don't know how to choose L and U value. could you give me some suggestions?

I know this depth is not enough compared to other successful sample for me. Their situation is something like: coverage: 66-70   meandepth: 20-35

thanks.
Cui

**Comment by cuixy1994** [comment]
The situation of this sample is as follows:

coverage: 61     meandepth: 4.5




I chosed the values of L=10  and U=260, the final analysis was the same.

I don't know how to choose L and U value. could you give me some suggestions?




I know this depth is not enough compared to other successful sample for me. Their situation is something like: coverage: 66-70   meandepth: 20-35




thanks.

Cui





































At 2022-02-08 17:50:24, "Kamil S. Jaron" ***@***.***> wrote:

Hi Cui,

I guess I should fix this error finally.

It is (till now every time) caused by L and U being too close to each other - The x axis of smudgeplot is minor / (major + minor), where major and minor are coverages of the more and less covered kmer in a k-mer pair. So if you selecting kmers that are 160 to 260x, then it the minimal value of minor / (major + minor) is 0.38, and causes that the whole left side of the plot would be blank.

The error itself is a problem because the algorithm needs some of points with coverage ratio lower than that and use it to guess the ploidy right, which is also the reason why I have not really made a decent workaround.

So for now I would recommend chosing better values of L and U. What is your expected 1n coverage approximately?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by KamilSJaron** [comment]
I usually plot k-mer spectra (usually by fitting naively a [genomescope model](http://qb.cshl.edu/genomescope/genomescope2.0/)). The plot usually is quite well indicative of how to chose L and U. L should be chosen so it cuts out majority of the error kmers in the dataset (red line in the model) and U should be so it does contain all the k-mers that are at least in four genomic copies (but you might want to increase this number for genomes that might have higher ploidy levels).

For example, in the histogram bellow I decided to chose L = 20 and U = 200. While U could have been a lot larger and it would not probably change much, the L is quite carefully chosen value - it is certainly not cutting too much of the first genomic peak, but it is quite well separating all the errors. The algorithm I wrote to determine L and U for the user is very simple and it will be overperformed by eyeballing the histogram which I encourage everyone to do.

![Mjav2_kmer_selection_from_kmer_profile](https://user-images.githubusercontent.com/8181573/153035719-44184f70-8c25-4b2f-b225-214732e026df.png)

Regarding your sample - I am not sure what you mean by coverage and meandepth, I was asking about the mean per-base or k-mer haploid coverage of your genome, e.g. the one above is ~45x, so the L will be fine around 20 or even 30x, because it does not cuts into the 1n genomic peak. Does it make sense?

P.S. I suppose closing of the issue was accidental.

**Comment by cuixy1994** [comment]
I get it! 
I'm talking about the ratio relative to the full genome (coverage, meandepth).

thanks.

**Comment by cuixy1994** [comment]
I get it! 
I'm talking about the ratio relative to the full genome (coverage, meandepth).

thanks.

**Comment by cuixy1994** [comment]
I get it! 

I'm talking about the ratio relative to the full genome (coverage, meandepth).




thanks.













At 2022-02-09 01:03:31, "Kamil S. Jaron" ***@***.***> wrote:

I usually plot k-mer spectra (usually by fitting naively a genomescope model). The plot usually is quite well indicative of how to chose L and U. L should be chosen so it cuts out majority of the error kmers in the dataset (red line in the model) and U should be so it does contain all the k-mers that are at least in four genomic copies (but you might want to increase this number for genomes that might have higher ploidy levels).

For example, in the histogram bellow I decided to chose L = 20 and U = 200. While U could have been a lot larger and it would not probably change much, the L is quite carefully chosen value - it is certainly not cutting too much of the first genomic peak, but it is quite well separating all the errors. The algorithm I wrote to determine L and U for the user is very simple and it will be overperformed by eyeballing the histogram which I encourage everyone to do.

Regarding your sample - I am not sure what you mean by coverage and meandepth, I was asking about the mean per-base or k-mer haploid coverage of your genome, e.g. the one above is ~45x, so the L will be fine around 20 or even 30x, because it does not cuts into the 1n genomic peak. Does it make sense?

P.S. I suppose closing of the issue was accidental.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
